apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-example-apps
  annotations:
    github.com/project-slug: dzemanov/argocd-example-apps
spec:
  type: other
  lifecycle: unknown
  owner: user:default/rhdhtest-11
